#pragma kernel ExternalForce
#pragma kernel Collision
#pragma kernel Predict
#pragma kernel Update
#pragma kernel StretchConstHorizontal
#pragma kernel StretchConstVertical
#pragma kernel BendConstHorizontal
#pragma kernel BendConstVertical
#pragma kernel StretchConstDiagonalRight
#pragma kernel StretchConstDiagonalLeft

#define PI 3.14159265359

struct Particle
{
    float3 x;
    float3 p;
    float3 v;
    float w;
};

RWStructuredBuffer<Particle> _Particles;

uint _NumParticles;

uint _NumWidth;
uint _NumHeight;
float _ParticleSpacing;

float3 _Gravity;
float _Damping;
float _Dt;
float3 _Anchor;

uint _Step;
float _KStretch;
float _KCompression;
float _KShear;
float _KShearCompression;

uint _StepX;
uint _StepY;
float _KBend;

[numthreads(64, 1, 1)]
void ExternalForce (uint id : SV_DispatchThreadID)
{
    if (id >= _NumParticles) return;

    // 重力を適用
    _Particles[id].v += _Gravity * _Dt;

    // 速度の減衰を適用
    _Particles[id].v *= _Damping;
}

[numthreads(64, 1, 1)]
void Collision (uint id : SV_DispatchThreadID)
{
    if (id >= _NumParticles) return;
}

[numthreads(64, 1, 1)]
void Predict (uint id : SV_DispatchThreadID)
{
    if (id >= _NumParticles) return;

    // 固定の場合は速度を0にしておく
    if (_Particles[id].w == 0.0)
    {
        _Particles[id].x = _Anchor;
        _Particles[id].p = _Anchor;
        _Particles[id].v = 0.0;
        return;
    }

    // 現在の位置と速度から、予測位置を計算
    _Particles[id].p = _Particles[id].x + _Particles[id].v * _Dt;
}

[numthreads(64, 1, 1)]
void Update (uint id : SV_DispatchThreadID)
{
    if (id >= _NumParticles) return;

    _Particles[id].v = (_Particles[id].p - _Particles[id].x) / _Dt;

    _Particles[id].x = _Particles[id].p;
}

void SolveStretch(uint pID0, uint pID1, float restLength, float kStr, float kComp)
{
    float3 p0 = _Particles[pID0].p;
    float3 p1 = _Particles[pID1].p;

    float3 p0p1 = p1 - p0;
    float p0p1Length = length(p0p1);

    if (p0p1Length < 1e-6) return;

    float w0 = _Particles[pID0].w;
    float w1 = _Particles[pID1].w;

    float3 gradC = p0p1 / p0p1Length;
    // 縮んでいる時は何もしない
    // float C = max(p0p1Length - restLength, 0);
    float C = p0p1Length - restLength;
    float s = C / ((w0 + w1) * dot(gradC, gradC));

    float3 deltaP0 = +s * w0 * gradC;
    float3 deltaP1 = -s * w1 * gradC;

    float k = (C >= 0.0) ? kStr : kComp;

    _Particles[pID0].p += deltaP0 * k;
    _Particles[pID1].p += deltaP1 * k;
}

[numthreads(64, 1, 1)]
void StretchConstHorizontal (uint id : SV_DispatchThreadID)
{
    // _Stepの値が0か1かで、拘束を適用するパーティクルの組み合わせが変わる
    uint pID0 = 2 * id + _Step;
    uint pID1 = pID0 + 1;

    if (pID1 >= _NumParticles) return;

    // p0が右端で、p0が左端になる場合は計算しない
    uint x0 = pID0 % _NumWidth;
    uint x1 = pID1 % _NumWidth;
    if (x0 > x1) return;

    // 初期状態の距離以上に伸びないように拘束する
    SolveStretch(pID0, pID1, _ParticleSpacing, _KStretch, _KCompression);
}

[numthreads(64, 1, 1)]
void StretchConstVertical (uint id : SV_DispatchThreadID)
{
    uint pID0 = id + (id / _NumWidth) * _NumWidth + _Step * _NumWidth;
    uint pid1 = pID0 + _NumWidth;

    if (pid1 >= _NumParticles) return;

    SolveStretch(pID0, pid1, _ParticleSpacing, _KStretch, _KCompression);
}

[numthreads(64, 1, 1)]
void StretchConstDiagonalRight(uint id : SV_DispatchThreadID)
{
    // Step = 0, 1 で競合しないように分割
    uint pID0 = 2 * id + _Step;
    uint pID1 = pID0 + _NumWidth + 1;

    if (pID1 >= _NumParticles) return;

    uint x0 = pID0 % _NumWidth;

    // 右端から次の行へ飛ぶ拘束を除外
    if (x0 + 1 >= _NumWidth) return;

    SolveStretch(
        pID0,
        pID1,
        _ParticleSpacing * sqrt(2.0),
        _KShear,
        _KShearCompression
    );
}

[numthreads(64, 1, 1)]
void StretchConstDiagonalLeft(uint id : SV_DispatchThreadID)
{
    uint pID0 = 2 * id + _Step;
    uint pID1 = pID0 + _NumWidth - 1;

    if (pID1 >= _NumParticles) return;

    uint x0 = pID0 % _NumWidth;

    // 左端から次の行の右端へ飛ぶ拘束を除外
    if (x0 == 0) return;

    SolveStretch(
        pID0,
        pID1,
        _ParticleSpacing * sqrt(2.0),
        _KShear,
        _KShearCompression
    );
}

// 共有辺を挟む、2つの三角面の曲げ拘束
void SolveBend(uint edgeID0, uint edgeID1, uint oppositeID0, uint oppositeID1, float restAngle, float k)
{
    float3 p0 = _Particles[edgeID0].p;
    float3 p1 = _Particles[edgeID1].p;
    float3 p2 = _Particles[oppositeID0].p;
    float3 p3 = _Particles[oppositeID1].p;

    float w0 = _Particles[edgeID0].w;
    float w1 = _Particles[edgeID1].w;
    float w2 = _Particles[oppositeID0].w;
    float w3 = _Particles[oppositeID1].w;

    // p0を原点とした相対座標
    float3 p0p1 = p1 - p0;
    float3 p0p2 = p2 - p0;
    float3 p0p3 = p3 - p0;

    float3 c12 = cross(p0p1, p0p2);
    float3 c13 = cross(p0p1, p0p3);

    float lc12 = length(c12);
    float lc13 = length(c13);

    // 三角形が潰れている時は計算しない
    if (lc12 < 1e-6 || lc13 < 1e-6) return;

    float3 n0 = c12 / lc12;
    float3 n1 = c13 / lc13;

    float d = clamp(dot(n0, n1), -1.0, 1.0);

    // 拘束勾配
    float3 q2 = (cross(p0p1, n1) + cross(n0, p0p1) * d) / lc12;

    float3 q3 = (cross(p0p1, n0) + cross(n1, p0p1) * d) / lc13;

    float3 q1 = -(cross(p0p2, n1) + cross(n0, p0p2) * d) / lc12 -(cross(p0p3, n0) + cross(n1, p0p3) * d) / lc13;

    float3 q0 = -q1 - q2 - q3;

    float denominator = w0 * dot(q0, q0) + w1 * dot(q1, q1) + w2 * dot(q2, q2) + w3 * dot(q3, q3);

    if (denominator < 1e-8) return;

    // 現在の二面角
    float angle = acos(d);

    // 曲げ拘束
    float C = angle - restAngle;

    // acosの微分項
    float sinAngle = sqrt(max(1.0 - d * d, 0.0));

    float s = -sinAngle * C / denominator;

    s *= k;

    float3 deltaP0 = w0 * s * q0;
    float3 deltaP1 = w1 * s * q1;
    float3 deltaP2 = w2 * s * q2;
    float3 deltaP3 = w3 * s * q3;

    _Particles[edgeID0].p     += deltaP0;
    _Particles[edgeID1].p     += deltaP1;
    _Particles[oppositeID0].p += deltaP2;
    _Particles[oppositeID1].p += deltaP3;
}

[numthreads(64, 1, 1)]
void BendConstHorizontal (uint id : SV_DispatchThreadID)
{
    uint numX = _NumWidth / 2;
    uint numY = _NumHeight / 2;

    uint ix = id % numX;
    uint iy = id / numX;

    if (iy >= numY) return;

    uint x = ix * 2 + _StepX;
    uint y = 1 + iy * 2 + _StepY;

    if (x + 1 >= _NumWidth || y + 1>= _NumHeight) return;

    uint edgeID0 = y * _NumWidth + x;
    uint edgeID1 = y * _NumWidth + x + 1;

    uint oppositeID0 = (y - 1) * _NumWidth + x;
    uint oppositeID1 = (y + 1) * _NumWidth + x + 1;

    SolveBend(edgeID0, edgeID1, oppositeID0, oppositeID1, PI, _KBend);
}

[numthreads(64, 1, 1)]
void BendConstVertical(uint id : SV_DispatchThreadID)
{
    uint numX = _NumWidth / 2;
    uint numY = _NumHeight / 2;

    uint ix = id % numX;
    uint iy = id / numX;

    if (iy >= numY) return;

    uint x = 1 + ix * 2 + _StepX;
    uint y = iy * 2 + _StepY;

    if (x + 1 >= _NumWidth || y + 1 >= _NumHeight) return;

    uint edgeID0 = y * _NumWidth + x;
    uint edgeID1 = (y + 1) * _NumWidth + x;

    uint oppositeID0 = y * _NumWidth + x - 1;
    uint oppositeID1 = (y + 1) * _NumWidth + x + 1;

    SolveBend(edgeID0, edgeID1, oppositeID0, oppositeID1, PI, _KBend);
}
